-- CreateEnum
CREATE TYPE "EtiquetaRegistro" AS ENUM ('REGISTRO_DIARIO', 'AUSENCIA', 'COORDINACION_FAMILIA', 'COORDINACION_COLEGIO', 'PARTICIPACION_FAMILIA', 'COORDINACION_PROFESIONALES', 'REVISION_OBJETIVOS', 'EVALUACION_INICIAL', 'SESION_GRUPAL', 'ALTA_TEMPORAL');

-- AlterTable
ALTER TABLE "registros_diarios" ADD COLUMN     "etiquetas" "EtiquetaRegistro"[] DEFAULT ARRAY['REGISTRO_DIARIO']::"EtiquetaRegistro"[];
